module CatalogoApp {
    // Define o array de bytes para empacotar os argumentos
    typedef sequence<octet> ByteArray;

    // A interface do seu serviço remoto
    interface ServicoCatalogo {
        ByteArray doOperation(in string objectRef, in long methodId, in ByteArray arguments);
    };
};