// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __Servico_hh__
#define __Servico_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_Servico
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_Servico
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_Servico
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE CatalogoApp

_CORBA_MODULE_BEG

  class ByteArray_var;

  class ByteArray : public _CORBA_Unbounded_Sequence_Octet {
  public:
    typedef ByteArray_var _var_type;
    inline ByteArray() {}
    inline ByteArray(const ByteArray& _s)
      : _CORBA_Unbounded_Sequence_Octet(_s) {}

    inline ByteArray(_CORBA_ULong _max)
      : _CORBA_Unbounded_Sequence_Octet(_max) {}
    inline ByteArray(_CORBA_ULong _max, _CORBA_ULong _len, ::CORBA::Octet* _val, _CORBA_Boolean _rel=0)
      : _CORBA_Unbounded_Sequence_Octet(_max, _len, _val, _rel) {}

  

    inline ByteArray& operator = (const ByteArray& _s) {
      _CORBA_Unbounded_Sequence_Octet::operator=(_s);
      return *this;
    }
  };

  class ByteArray_out;

  class ByteArray_var {
  public:
    inline ByteArray_var() : _pd_seq(0) {}
    inline ByteArray_var(ByteArray* _s) : _pd_seq(_s) {}
    inline ByteArray_var(const ByteArray_var& _s) {
      if (_s._pd_seq)  _pd_seq = new ByteArray(*_s._pd_seq);
      else             _pd_seq = 0;
    }
    inline ~ByteArray_var() { if (_pd_seq)  delete _pd_seq; }
      
    inline ByteArray_var& operator = (ByteArray* _s) {
      if (_pd_seq)  delete _pd_seq;
      _pd_seq = _s;
      return *this;
    }
    inline ByteArray_var& operator = (const ByteArray_var& _s) {
      if (&_s != this) {
        if (_s._pd_seq) {
          if (!_pd_seq)  _pd_seq = new ByteArray;
          *_pd_seq = *_s._pd_seq;
        }
        else if (_pd_seq) {
          delete _pd_seq;
          _pd_seq = 0;
        }
      }
      return *this;
    }
    inline ::CORBA::Octet& operator [] (_CORBA_ULong _s) {
      return (*_pd_seq)[_s];
    }

  

    inline ByteArray* operator -> () { return _pd_seq; }
    inline const ByteArray* operator -> () const { return _pd_seq; }
#if defined(__GNUG__)
    inline operator ByteArray& () const { return *_pd_seq; }
#else
    inline operator const ByteArray& () const { return *_pd_seq; }
    inline operator ByteArray& () { return *_pd_seq; }
#endif
      
    inline const ByteArray& in() const { return *_pd_seq; }
    inline ByteArray&       inout()    { return *_pd_seq; }
    inline ByteArray*&      out() {
      if (_pd_seq) { delete _pd_seq; _pd_seq = 0; }
      return _pd_seq;
    }
    inline ByteArray* _retn() { ByteArray* tmp = _pd_seq; _pd_seq = 0; return tmp; }
      
    friend class ByteArray_out;
    
  private:
    ByteArray* _pd_seq;
  };

  class ByteArray_out {
  public:
    inline ByteArray_out(ByteArray*& _s) : _data(_s) { _data = 0; }
    inline ByteArray_out(ByteArray_var& _s)
      : _data(_s._pd_seq) { _s = (ByteArray*) 0; }
    inline ByteArray_out(const ByteArray_out& _s) : _data(_s._data) {}
    inline ByteArray_out& operator = (const ByteArray_out& _s) {
      _data = _s._data;
      return *this;
    }
    inline ByteArray_out& operator = (ByteArray* _s) {
      _data = _s;
      return *this;
    }
    inline operator ByteArray*&()  { return _data; }
    inline ByteArray*& ptr()       { return _data; }
    inline ByteArray* operator->() { return _data; }

    inline ::CORBA::Octet& operator [] (_CORBA_ULong _i) {
      return (*_data)[_i];
    }

  

    ByteArray*& _data;

  private:
    ByteArray_out();
    ByteArray_out& operator=(const ByteArray_var&);
  };

#ifndef __CatalogoApp_mServicoCatalogo__
#define __CatalogoApp_mServicoCatalogo__
  class ServicoCatalogo;
  class _objref_ServicoCatalogo;
  class _impl_ServicoCatalogo;
  
  typedef _objref_ServicoCatalogo* ServicoCatalogo_ptr;
  typedef ServicoCatalogo_ptr ServicoCatalogoRef;

  class ServicoCatalogo_Helper {
  public:
    typedef ServicoCatalogo_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_ServicoCatalogo, ServicoCatalogo_Helper> ServicoCatalogo_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_ServicoCatalogo,ServicoCatalogo_Helper > ServicoCatalogo_out;

#endif

  // interface ServicoCatalogo
  class ServicoCatalogo {
  public:
    // Declarations for this interface type.
    typedef ServicoCatalogo_ptr _ptr_type;
    typedef ServicoCatalogo_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_ServicoCatalogo :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    ByteArray* doOperation(const char* objectRef, ::CORBA::Long methodId, const ::CatalogoApp::ByteArray& arguments);

    // Constructors
    inline _objref_ServicoCatalogo()  { _PR_setobj(0); }  // nil
    _objref_ServicoCatalogo(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_ServicoCatalogo();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_ServicoCatalogo(const _objref_ServicoCatalogo&);
    _objref_ServicoCatalogo& operator = (const _objref_ServicoCatalogo&);
    // not implemented

    friend class ServicoCatalogo;
  };

  class _pof_ServicoCatalogo : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_ServicoCatalogo() : _OMNI_NS(proxyObjectFactory)(ServicoCatalogo::_PD_repoId) {}
    virtual ~_pof_ServicoCatalogo();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_ServicoCatalogo :
    public virtual omniServant
  {
  public:
    virtual ~_impl_ServicoCatalogo();

    virtual ByteArray* doOperation(const char* objectRef, ::CORBA::Long methodId, const ::CatalogoApp::ByteArray& arguments) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_CatalogoApp
_CORBA_MODULE_BEG

  class ServicoCatalogo :
    public virtual CatalogoApp::_impl_ServicoCatalogo,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~ServicoCatalogo();

    inline ::CatalogoApp::ServicoCatalogo_ptr _this() {
      return (::CatalogoApp::ServicoCatalogo_ptr) _do_this(::CatalogoApp::ServicoCatalogo::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CatalogoApp
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
CatalogoApp::ServicoCatalogo::_marshalObjRef(::CatalogoApp::ServicoCatalogo_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_Servico
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_Servico
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_Servico
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_Servico
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_Servico
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_Servico
#endif

#endif  // __Servico_hh__

