# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: produto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'produto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduto.proto\x12\x04loja\"V\n\x07Produto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\r\n\x05preco\x18\x04 \x01(\x02\x12\x0f\n\x07\x65stoque\x18\x05 \x01(\x05\"\x17\n\tProdutoId\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\rListaProdutos\x12\x1f\n\x08produtos\x18\x01 \x03(\x0b\x32\r.loja.Produto\"\x07\n\x05\x45mpty2\xa0\x01\n\x0eProdutoService\x12,\n\nGetProduto\x12\x0f.loja.ProdutoId\x1a\r.loja.Produto\x12\x32\n\x0eListarProdutos\x12\x0b.loja.Empty\x1a\x13.loja.ListaProdutos\x12,\n\x0c\x43riarProduto\x12\r.loja.Produto\x1a\r.loja.Produtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'produto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUTO']._serialized_start=23
  _globals['_PRODUTO']._serialized_end=109
  _globals['_PRODUTOID']._serialized_start=111
  _globals['_PRODUTOID']._serialized_end=134
  _globals['_LISTAPRODUTOS']._serialized_start=136
  _globals['_LISTAPRODUTOS']._serialized_end=184
  _globals['_EMPTY']._serialized_start=186
  _globals['_EMPTY']._serialized_end=193
  _globals['_PRODUTOSERVICE']._serialized_start=196
  _globals['_PRODUTOSERVICE']._serialized_end=356
# @@protoc_insertion_point(module_scope)
