# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import produto_pb2 as produto__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in produto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProdutoServiceStub(object):
    """==================== SERVIÇO DE PRODUTOS ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduto = channel.unary_unary(
                '/loja.ProdutoService/GetProduto',
                request_serializer=produto__pb2.ProdutoId.SerializeToString,
                response_deserializer=produto__pb2.Produto.FromString,
                _registered_method=True)
        self.ListarProdutos = channel.unary_unary(
                '/loja.ProdutoService/ListarProdutos',
                request_serializer=produto__pb2.Empty.SerializeToString,
                response_deserializer=produto__pb2.ListaProdutos.FromString,
                _registered_method=True)
        self.AtualizarEstoque = channel.unary_unary(
                '/loja.ProdutoService/AtualizarEstoque',
                request_serializer=produto__pb2.AtualizarEstoqueRequest.SerializeToString,
                response_deserializer=produto__pb2.Produto.FromString,
                _registered_method=True)


class ProdutoServiceServicer(object):
    """==================== SERVIÇO DE PRODUTOS ====================
    """

    def GetProduto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarProdutos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarEstoque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProdutoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProduto': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduto,
                    request_deserializer=produto__pb2.ProdutoId.FromString,
                    response_serializer=produto__pb2.Produto.SerializeToString,
            ),
            'ListarProdutos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarProdutos,
                    request_deserializer=produto__pb2.Empty.FromString,
                    response_serializer=produto__pb2.ListaProdutos.SerializeToString,
            ),
            'AtualizarEstoque': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarEstoque,
                    request_deserializer=produto__pb2.AtualizarEstoqueRequest.FromString,
                    response_serializer=produto__pb2.Produto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loja.ProdutoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loja.ProdutoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProdutoService(object):
    """==================== SERVIÇO DE PRODUTOS ====================
    """

    @staticmethod
    def GetProduto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loja.ProdutoService/GetProduto',
            produto__pb2.ProdutoId.SerializeToString,
            produto__pb2.Produto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarProdutos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loja.ProdutoService/ListarProdutos',
            produto__pb2.Empty.SerializeToString,
            produto__pb2.ListaProdutos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarEstoque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loja.ProdutoService/AtualizarEstoque',
            produto__pb2.AtualizarEstoqueRequest.SerializeToString,
            produto__pb2.Produto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ClienteServiceStub(object):
    """==================== SERVIÇO DE CLIENTES ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarCliente = channel.unary_unary(
                '/loja.ClienteService/RegistrarCliente',
                request_serializer=produto__pb2.Cliente.SerializeToString,
                response_deserializer=produto__pb2.Cliente.FromString,
                _registered_method=True)
        self.GetCliente = channel.unary_unary(
                '/loja.ClienteService/GetCliente',
                request_serializer=produto__pb2.ClienteId.SerializeToString,
                response_deserializer=produto__pb2.Cliente.FromString,
                _registered_method=True)
        self.ListarClientes = channel.unary_unary(
                '/loja.ClienteService/ListarClientes',
                request_serializer=produto__pb2.Empty.SerializeToString,
                response_deserializer=produto__pb2.ListaClientes.FromString,
                _registered_method=True)


class ClienteServiceServicer(object):
    """==================== SERVIÇO DE CLIENTES ====================
    """

    def RegistrarCliente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCliente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarClientes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClienteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarCliente': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarCliente,
                    request_deserializer=produto__pb2.Cliente.FromString,
                    response_serializer=produto__pb2.Cliente.SerializeToString,
            ),
            'GetCliente': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCliente,
                    request_deserializer=produto__pb2.ClienteId.FromString,
                    response_serializer=produto__pb2.Cliente.SerializeToString,
            ),
            'ListarClientes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarClientes,
                    request_deserializer=produto__pb2.Empty.FromString,
                    response_serializer=produto__pb2.ListaClientes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loja.ClienteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loja.ClienteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClienteService(object):
    """==================== SERVIÇO DE CLIENTES ====================
    """

    @staticmethod
    def RegistrarCliente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loja.ClienteService/RegistrarCliente',
            produto__pb2.Cliente.SerializeToString,
            produto__pb2.Cliente.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCliente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loja.ClienteService/GetCliente',
            produto__pb2.ClienteId.SerializeToString,
            produto__pb2.Cliente.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarClientes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loja.ClienteService/ListarClientes',
            produto__pb2.Empty.SerializeToString,
            produto__pb2.ListaClientes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PedidoServiceStub(object):
    """==================== SERVIÇO DE PEDIDOS ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarPedido = channel.unary_unary(
                '/loja.PedidoService/CriarPedido',
                request_serializer=produto__pb2.Pedido.SerializeToString,
                response_deserializer=produto__pb2.Pedido.FromString,
                _registered_method=True)
        self.GetPedido = channel.unary_unary(
                '/loja.PedidoService/GetPedido',
                request_serializer=produto__pb2.PedidoId.SerializeToString,
                response_deserializer=produto__pb2.Pedido.FromString,
                _registered_method=True)
        self.ListarPedidos = channel.unary_unary(
                '/loja.PedidoService/ListarPedidos',
                request_serializer=produto__pb2.ClienteId.SerializeToString,
                response_deserializer=produto__pb2.ListaPedidos.FromString,
                _registered_method=True)
        self.AtualizarStatusPedido = channel.unary_unary(
                '/loja.PedidoService/AtualizarStatusPedido',
                request_serializer=produto__pb2.AtualizarStatusRequest.SerializeToString,
                response_deserializer=produto__pb2.Pedido.FromString,
                _registered_method=True)


class PedidoServiceServicer(object):
    """==================== SERVIÇO DE PEDIDOS ====================
    """

    def CriarPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPedidos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarStatusPedido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PedidoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarPedido,
                    request_deserializer=produto__pb2.Pedido.FromString,
                    response_serializer=produto__pb2.Pedido.SerializeToString,
            ),
            'GetPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPedido,
                    request_deserializer=produto__pb2.PedidoId.FromString,
                    response_serializer=produto__pb2.Pedido.SerializeToString,
            ),
            'ListarPedidos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPedidos,
                    request_deserializer=produto__pb2.ClienteId.FromString,
                    response_serializer=produto__pb2.ListaPedidos.SerializeToString,
            ),
            'AtualizarStatusPedido': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarStatusPedido,
                    request_deserializer=produto__pb2.AtualizarStatusRequest.FromString,
                    response_serializer=produto__pb2.Pedido.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loja.PedidoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loja.PedidoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PedidoService(object):
    """==================== SERVIÇO DE PEDIDOS ====================
    """

    @staticmethod
    def CriarPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loja.PedidoService/CriarPedido',
            produto__pb2.Pedido.SerializeToString,
            produto__pb2.Pedido.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loja.PedidoService/GetPedido',
            produto__pb2.PedidoId.SerializeToString,
            produto__pb2.Pedido.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPedidos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loja.PedidoService/ListarPedidos',
            produto__pb2.ClienteId.SerializeToString,
            produto__pb2.ListaPedidos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarStatusPedido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loja.PedidoService/AtualizarStatusPedido',
            produto__pb2.AtualizarStatusRequest.SerializeToString,
            produto__pb2.Pedido.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
