package CatalogoApp;


/**
* CatalogoApp/ByteArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalogo.idl
* Domingo, 17 de Maio de 2026 19h25min44s BRT
*/


// Define o array de bytes para empacotar os argumentos (JSON/Protobuf)
public final class ByteArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public ByteArrayHolder ()
  {
  }

  public ByteArrayHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CatalogoApp.ByteArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CatalogoApp.ByteArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CatalogoApp.ByteArrayHelper.type ();
  }

}
