package CatalogoApp;


/**
* CatalogoApp/ServicoCatalogoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalogo.idl
* Domingo, 17 de Maio de 2026 19h25min44s BRT
*/


// A interface do seu serviço remoto
public interface ServicoCatalogoOperations 
{
  byte[] doOperation (String objectRef, int methodId, byte[] arguments);
} // interface ServicoCatalogoOperations
