package CatalogoApp;

/**
* CatalogoApp/ServicoCatalogoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalogo.idl
* Domingo, 17 de Maio de 2026 19h25min44s BRT
*/


// A interface do seu serviço remoto
public final class ServicoCatalogoHolder implements org.omg.CORBA.portable.Streamable
{
  public CatalogoApp.ServicoCatalogo value = null;

  public ServicoCatalogoHolder ()
  {
  }

  public ServicoCatalogoHolder (CatalogoApp.ServicoCatalogo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CatalogoApp.ServicoCatalogoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CatalogoApp.ServicoCatalogoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CatalogoApp.ServicoCatalogoHelper.type ();
  }

}
