package CatalogoApp;


/**
* CatalogoApp/ServicoCatalogoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalogo.idl
* Domingo, 17 de Maio de 2026 19h25min44s BRT
*/


// A interface do seu serviço remoto
public abstract class ServicoCatalogoPOA extends org.omg.PortableServer.Servant
 implements CatalogoApp.ServicoCatalogoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("doOperation", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CatalogoApp/ServicoCatalogo/doOperation
       {
         String objectRef = in.read_string ();
         int methodId = in.read_long ();
         byte arguments[] = CatalogoApp.ByteArrayHelper.read (in);
         byte $result[] = null;
         $result = this.doOperation (objectRef, methodId, arguments);
         out = $rh.createReply();
         CatalogoApp.ByteArrayHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CatalogoApp/ServicoCatalogo:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServicoCatalogo _this() 
  {
    return ServicoCatalogoHelper.narrow(
    super._this_object());
  }

  public ServicoCatalogo _this(org.omg.CORBA.ORB orb) 
  {
    return ServicoCatalogoHelper.narrow(
    super._this_object(orb));
  }


} // class ServicoCatalogoPOA
