package CatalogoApp;


/**
* CatalogoApp/ServicoCatalogo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from catalogo.idl
* Domingo, 17 de Maio de 2026 19h25min44s BRT
*/


// A interface do seu serviço remoto
public interface ServicoCatalogo extends ServicoCatalogoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServicoCatalogo
