// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "Servico.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



CatalogoApp::ServicoCatalogo_ptr CatalogoApp::ServicoCatalogo_Helper::_nil() {
  return ::CatalogoApp::ServicoCatalogo::_nil();
}

::CORBA::Boolean CatalogoApp::ServicoCatalogo_Helper::is_nil(::CatalogoApp::ServicoCatalogo_ptr p) {
  return ::CORBA::is_nil(p);

}

void CatalogoApp::ServicoCatalogo_Helper::release(::CatalogoApp::ServicoCatalogo_ptr p) {
  ::CORBA::release(p);
}

void CatalogoApp::ServicoCatalogo_Helper::marshalObjRef(::CatalogoApp::ServicoCatalogo_ptr obj, cdrStream& s) {
  ::CatalogoApp::ServicoCatalogo::_marshalObjRef(obj, s);
}

CatalogoApp::ServicoCatalogo_ptr CatalogoApp::ServicoCatalogo_Helper::unmarshalObjRef(cdrStream& s) {
  return ::CatalogoApp::ServicoCatalogo::_unmarshalObjRef(s);
}

void CatalogoApp::ServicoCatalogo_Helper::duplicate(::CatalogoApp::ServicoCatalogo_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

CatalogoApp::ServicoCatalogo_ptr
CatalogoApp::ServicoCatalogo::_duplicate(::CatalogoApp::ServicoCatalogo_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

CatalogoApp::ServicoCatalogo_ptr
CatalogoApp::ServicoCatalogo::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


CatalogoApp::ServicoCatalogo_ptr
CatalogoApp::ServicoCatalogo::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

CatalogoApp::ServicoCatalogo_ptr
CatalogoApp::ServicoCatalogo::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_ServicoCatalogo _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_ServicoCatalogo* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_ServicoCatalogo;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* CatalogoApp::ServicoCatalogo::_PD_repoId = "IDL:CatalogoApp/ServicoCatalogo:1.0";


CatalogoApp::_objref_ServicoCatalogo::~_objref_ServicoCatalogo() {
  
}


CatalogoApp::_objref_ServicoCatalogo::_objref_ServicoCatalogo(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::CatalogoApp::ServicoCatalogo::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
CatalogoApp::_objref_ServicoCatalogo::_ptrToObjRef(const char* id)
{
  if (id == ::CatalogoApp::ServicoCatalogo::_PD_repoId)
    return (::CatalogoApp::ServicoCatalogo_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::CatalogoApp::ServicoCatalogo::_PD_repoId))
    return (::CatalogoApp::ServicoCatalogo_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for CatalogoApp::ServicoCatalogo::doOperation

// Proxy call descriptor class. Mangled signature:
//  _cCatalogoApp_mByteArray_i_cstring_i_clong_i_cCatalogoApp_mByteArray
class _0RL_cd_b19cd8b403fda1e4_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_b19cd8b403fda1e4_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::Long arg_1;
  CatalogoApp::ByteArray_var arg_2_;
  const CatalogoApp::ByteArray* arg_2;
  CatalogoApp::ByteArray_var result;
};

void _0RL_cd_b19cd8b403fda1e4_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  arg_1 >>= _n;
  (const CatalogoApp::ByteArray&) *arg_2 >>= _n;

}

void _0RL_cd_b19cd8b403fda1e4_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  (::CORBA::Long&)arg_1 <<= _n;
  arg_2_ = new CatalogoApp::ByteArray;
  (CatalogoApp::ByteArray&)arg_2_ <<= _n;
  arg_2 = &arg_2_.in();

}

void _0RL_cd_b19cd8b403fda1e4_00000000::marshalReturnedValues(cdrStream& _n)
{
  (const CatalogoApp::ByteArray&) result >>= _n;

}

void _0RL_cd_b19cd8b403fda1e4_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new CatalogoApp::ByteArray;
  (CatalogoApp::ByteArray&)result <<= _n;

}

const char* const _0RL_cd_b19cd8b403fda1e4_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_b19cd8b403fda1e4_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_b19cd8b403fda1e4_00000000* tcd = (_0RL_cd_b19cd8b403fda1e4_00000000*)cd;
  CatalogoApp::_impl_ServicoCatalogo* impl = (CatalogoApp::_impl_ServicoCatalogo*) svnt->_ptrToInterface(CatalogoApp::ServicoCatalogo::_PD_repoId);
  tcd->result = impl->doOperation(tcd->arg_0, tcd->arg_1, *tcd->arg_2);


}

CatalogoApp::ByteArray* CatalogoApp::_objref_ServicoCatalogo::doOperation(const char* objectRef, ::CORBA::Long methodId, const ::CatalogoApp::ByteArray& arguments)
{
  _0RL_cd_b19cd8b403fda1e4_00000000 _call_desc(_0RL_lcfn_b19cd8b403fda1e4_10000000, "doOperation", 12);
  _call_desc.arg_0 = objectRef;
  _call_desc.arg_1 = methodId;
  _call_desc.arg_2 = &(::CatalogoApp::ByteArray&) arguments;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}

CatalogoApp::_pof_ServicoCatalogo::~_pof_ServicoCatalogo() {}


omniObjRef*
CatalogoApp::_pof_ServicoCatalogo::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::CatalogoApp::_objref_ServicoCatalogo(ior, id);
}


::CORBA::Boolean
CatalogoApp::_pof_ServicoCatalogo::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::CatalogoApp::ServicoCatalogo::_PD_repoId))
    return 1;
  
  return 0;
}

const CatalogoApp::_pof_ServicoCatalogo _the_pof_CatalogoApp_mServicoCatalogo;

CatalogoApp::_impl_ServicoCatalogo::~_impl_ServicoCatalogo() {}


::CORBA::Boolean
CatalogoApp::_impl_ServicoCatalogo::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "doOperation")) {

    _0RL_cd_b19cd8b403fda1e4_00000000 _call_desc(_0RL_lcfn_b19cd8b403fda1e4_10000000, "doOperation", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
CatalogoApp::_impl_ServicoCatalogo::_ptrToInterface(const char* id)
{
  if (id == ::CatalogoApp::ServicoCatalogo::_PD_repoId)
    return (::CatalogoApp::_impl_ServicoCatalogo*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::CatalogoApp::ServicoCatalogo::_PD_repoId))
    return (::CatalogoApp::_impl_ServicoCatalogo*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
CatalogoApp::_impl_ServicoCatalogo::_mostDerivedRepoId()
{
  return ::CatalogoApp::ServicoCatalogo::_PD_repoId;
}

POA_CatalogoApp::ServicoCatalogo::~ServicoCatalogo() {}

